# Generated by Django 5.2.3 on 2025-06-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0002_alter_gallery_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='city',
            field=models.CharField(default=str, max_length=50),
            preserve_default=False,
        ),
    ]
