# Generated by Django 5.2.3 on 2025-07-01 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0003_gallery_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='memories',
            field=models.CharField(default=str, max_length=256),
            preserve_default=False,
        ),
    ]
