# Generated by Django 5.2.3 on 2025-07-01 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0005_gallery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargingsession',
            name='station',
        ),
        migrations.RemoveField(
            model_name='chargingsession',
            name='user',
        ),
        migrations.DeleteModel(
            name='Station',
        ),
        migrations.DeleteModel(
            name='ChargingSession',
        ),
    ]
