# Generated by Django 5.2.3 on 2025-07-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0006_remove_chargingsession_station_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='date',
            field=models.DateField(),
        ),
    ]
